apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
