apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-petclinic-service
  labels:
    app: petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: petclinic
